#!/usr/bin/env python3

import argparse
import csv
import os
import re

from tqdm import tqdm
from vllm import LLM, SamplingParams

from .utils import extract_quote_context, normalize_model_name


PROMPT_TEMPLATE = """
We're doing topic modeling and determining whether the following quote within the
<document> tags is relevant to the topic {Topic}.

We want you to determine whether to reject the quote.
It should be rejected if it
- Is not related to the topic
- Is a promotional message
- Is a public service announcement
- Is theme music or similar

Determine whether the content in <document> tags falls in any of those categories.
If so, answer with a single word yes. Otherwise, answer with a single word no.

{Document}
"""

SYSTEM_PROMPT = """
You are a helpful assistant. After any explanation, give a one-word yes or no answer.
"""

YES_PATTERN = re.compile(r'[^\n\r]*(y(?:es)?)[^\n\r]*$', flags=re.I)

SENTINELS = ["it is an advertisement"]

def read_topic_quotes(paths):
	rows = []
	for path in paths:
		with open(path, newline="") as source:
			rows.extend(csv.DictReader(source))
	return rows


def main(raw_args=None):
	parser = argparse.ArgumentParser(description="Vote on whether topic quotes are advertisements")
	parser.add_argument("-i", "--input", dest="inputs", nargs="+", type=os.path.abspath,
						help="topic_quotes.csv files generated by gen.py")
	parser.add_argument("-o", "--output", type=os.path.abspath)
	parser.add_argument("--model", default="openai/gpt-oss-120b")
	parser.add_argument("--max-model-len", type=int, default=2048)
	parser.add_argument("--max-num-seqs", type=int, default=8)
	args = parser.parse_args(raw_args)

	model_name = args.model
	normalized_name = normalize_model_name(model_name)

	output_path = args.output or os.path.abspath(
		f"out/{normalized_name}_votes.csv"
	)

	rows = read_topic_quotes(args.input)
	conversations = [
		[
			{"role": "system", "content": SYSTEM_PROMPT},
			{"role": "user", "content": PROMPT_TEMPLATE.format(
				Topic=row["topic"],
				Document=extract_quote_context(row)
			)},
		]
		for row in tqdm(rows, desc="Building quote contexts")
	]

	llm = LLM(
		model=model_name,
		max_num_seqs=args.max_num_seqs,
		max_model_len=args.max_model_len,
		gpu_memory_utilization=0.95,
	)
	sampling_params = SamplingParams(temperature=0.0, max_tokens=1024)
	outputs = llm.chat(conversations, sampling_params=sampling_params, use_tqdm=True)
	responses = [o.outputs[0].text for o in outputs]
	sure_filter = [bool(YES_PATTERN.search(res)) or any(s in res for s in SENTINELS) for res in responses]

	os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
	with open(output_path, "w", newline="") as destination:
		writer = csv.writer(destination)
		writer.writerow([f"{normalize_model_name}--rejected"])
		writer.writerows([[rejected] for rejected in sure_filter])


if __name__ == "__main__":
	main()
