#!/usr/bin/env python3

import sys
import csv
import argparse
import os
import glob
import re
from typing import Iterable, Any, Generator


# A question mark, exclamation point, or period (that isn't part of an ellipse), followed by optional quotations, followed by a newline
SEGMENT_END = re.compile(r"(\?|\!|(?<!\.\.)\.)" + "(\"|\')*$")

assert     SEGMENT_END.search("I end with an exclamation point!")
assert     SEGMENT_END.search("\"I end with an exclamation point!\"")
assert     SEGMENT_END.search("\'I end with an exclamation point!\'")
assert     SEGMENT_END.search("I end with a period.")
assert     SEGMENT_END.search("I end with a question mark?")
assert not SEGMENT_END.search("I end with a an ellipse...")

def regex_segment(rows: Iterable[Any]) -> Generator[Any, None, None]:
    subrows = []
    for row in rows:
        subrows.append(row)
        if SEGMENT_END.search(row['text']):
            yield {
                "text": ''.join([sub['text'] for sub in subrows]),
                "start": subrows[0]['start'],
                "end": subrows[-1]['end']
            }
            subrows = []
    if subrows:
        yield {
                "text": ''.join([sub['text'] for sub in subrows]),
                "start": subrows[0]['start'],
                "end": subrows[-1]['end']
            }

def make_model_segment(model_name):
    from wtpsplit import SaT
    import numpy as np
    sat = SaT(model_name)
    sat.cuda()
    threshold = 0.25 # Had to look at the source code to find this
    def seg_func(rows):
        rows = list(rows)
        cum_lens = np.cumsum([len(row['text']) for row in rows]).tolist()
        start_times = [row['start'] for row in rows]
        end_times   = [row['end'] for row in rows]

        joined_text = ''.join(row['text'] for row in rows)
        probs = next(sat.predict_proba([joined_text]))
        bound_inds = np.where(probs > threshold)[0].tolist()

        assert bound_inds


        seg_start = 0
        start_time = 0
        last_row = 0
        for bound_ind in bound_inds:
            cur_row = next(filter(lambda row_ind: bound_ind < cum_lens[row_ind], range(last_row, len(rows))))
            yield {
                "text": joined_text[seg_start:bound_ind+1],
                "start": start_time,
                "end" : end_times[cur_row]
            }
            seg_start = bound_ind + 1
            last_row = cur_row

            # Boundary falls right at the end of a row
            # Need to increment to the next start time
            #  Boundary falls at end of row           # and it isn't the last row
            if bound_ind == cum_lens[cur_row] - 1 and cur_row < len(rows) - 1:
                start_time = start_times[cur_row + 1]
            else:
                start_time = start_times[cur_row]

        if bound_ind < len(joined_text) - 1:
            yield {
                "text" : joined_text[bound_ind:],
                "start": start_times[-1],
                "end"  : end_times[-1]
            }
    return seg_func


def main(raw_args=None):
    parser = argparse.ArgumentParser(description="Resegment the text generated by the audio transcription")
    parser.add_argument("--strategy", choices=("regex",'neural'), default="neural", help="What algorithm to use for the resegmenting")
    parser.add_argument("-i", default="transcribe_out/")
    parser.add_argument("-o", default="resegment_out/")
    args = parser.parse_args()

    in_dir = args.i
    out_dir = args.o

    if args.strategy == 'regex':
        seg_func = regex_segment
    elif args.strategy == 'neural':
        seg_func = make_model_segment("sat-12l-sm")
    else:
        print(f"Invalid strategy {args.strategy}")

    in_paths = glob.glob(os.path.join(in_dir, "**", "*.csv"))
    for in_path in in_paths:

        with open(in_path, 'r') as r:
            in_rows = list(csv.DictReader(r))
        out_rows = list(seg_func(in_rows))

        out_path = os.path.join(out_dir, os.path.dirname(os.path.relpath(in_path, in_dir)), os.path.basename(in_path))
        os.makedirs(os.path.dirname(out_path), exist_ok=True)
        if out_rows:
            print(f"Writing {out_path}")
            with open(out_path, 'w') as w:
                writer = csv.DictWriter(w, fieldnames=['start', 'end', 'text'])
                writer.writeheader()
                writer.writerows(out_rows)
        else:
            print(f"Warning: No segments for {in_path}", file=sys.stderr)
        break

if __name__ == "__main__":
    main()