#!/usr/bin/env python3

import sys
import csv
import argparse
import os
import glob
import re
from typing import Iterable, Any, Generator




# A question mark, exclamation point, or period (that isn't part of an ellipse), followed by optional quotations, followed by a newline
SEGMENT_END = re.compile(r"(\?|\!|(?<!\.\.)\.)" + "(\"|\')*$")

assert     SEGMENT_END.search("I end with an exclamation point!")
assert     SEGMENT_END.search("\"I end with an exclamation point!\"")
assert     SEGMENT_END.search("\'I end with an exclamation point!\'")
assert     SEGMENT_END.search("I end with a period.")
assert     SEGMENT_END.search("I end with a question mark?")
assert not SEGMENT_END.search("I end with a an ellipse...")

def regex_segment(rows: Iterable[Any]) -> Generator[Any, None, None]:
    subrows = []
    for row in rows:
        subrows.append(row)
        if SEGMENT_END.search(row['text']):
            yield {
                "text": ''.join([sub['text'] for sub in subrows]),
                "start": subrows[0]['start'],
                "end": subrows[-1]['end']
            }
            subrows = []
    if subrows:
        yield {
                "text": ''.join([sub['text'] for sub in subrows]),
                "start": subrows[0]['start'],
                "end": subrows[-1]['end']
            }

def make_model_segment(model_name):
    from wtpsplit import SaT
    import numpy as np
    sat = SaT(model_name)
    threshold = 0.25 # Had to look at the source code to find this
    def seg_func(rows):
        rows = list(rows)
        cum_lens = np.cumsum([len(row['text']) for row in rows]).tolist()
        start_times = [row['start'] for row in rows]
        end_times   = [row['end'] for row in rows]
        probs = next( sat.predict_proba([''.join(row['text'] for row in rows)]) )
        bound_inds = np.where(probs > threshold)[0].tolist()

        last_row = -1
        start_time = 0
        for i, bound_ind in enumerate(bound_inds):
            end_row = next(filter(lambda row_ind: bound_ind > cum_lens[row_ind], range(last_row, len(rows))))
            if end_row is not None:

                pass

                last_row = end_row
            else:
                pass


def main(raw_args=None):
    parser = argparse.ArgumentParser(description="Resegment the text generated by the audio transcription")
    parser.add_argument("--strategy", choices=("regex",), default="regex", help="What algorithm to use for the resegmenting")
    parser.add_argument("-i", default="transcribe_out/")
    parser.add_argument("-o", default="resegment_out/")
    args = parser.parse_args()

    in_dir = args.i
    out_dir = args.o

    if args.strategy == 'regex':
        seg_func = regex_segment
    else:
        print(f"Invalid strategy {args.strategy}")

    in_paths = glob.glob(os.path.join(in_dir, "**", "*.csv"))
    for in_path in in_paths:

        with open(in_path, 'r') as r:
            in_rows = list(csv.DictReader(r))
        out_rows = list(seg_func(in_rows))

        out_path = os.path.join(out_dir, os.path.dirname(os.path.relpath(in_path, in_dir)), os.path.basename(in_path))
        os.makedirs(os.path.dirname(out_path), exist_ok=True)
        if out_rows:
            print(f"Writing {out_path}")
            with open(out_path, 'w') as w:
                writer = csv.DictWriter(w, fieldnames=list(out_rows[0]))
                writer.writeheader()
                writer.writerows(out_rows)
        else:
            print(f"Warning: No segments for {in_path}", file=sys.stderr)
        break

if __name__ == "__main__":
    main()